spring.application.name=ncsmap
server.port=8090

# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# LOG
logging.level.com.ncsmap=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# ?? ???
file.upload-dir=D:/ncsmap/uploads/profile
file.access-url=/uploads/profile

# ??? ??? ?? ?? ??
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB